### ISSUE TITLE
Question about grab angles

### ISSUE THREAD

**Issue by friesofdoom** [ThatFatKidsMom/Avatar-Prop#10]
Not an issue, but is it possible for me to modify the prop so that it remains in my hand at whatever angle it was at when I picked it up rather than snapping to a predefined angle?

Thanks 👍

**Comment by ThatFatKidsMom** [comment]
Should be possible if your familiar with how to animate constraints in a way to maintain its offset when comparing its last rotation to the the rotation of the hand although it would instead have a snapping effect to its last known rotation rather than snapping to a predefined angle. It would probably be a pretty nice effect though and be a bit more prop like. Its late so I may be a bit off but it might require changing the hierarchy a bit or at least adding some more objects to be able to handle the rotation aspect of things... but overall not a bad idea that should be doable. I have some other projects I'm working on atm but I might end up coming back to this and adding a prefab that has this behavior into the package.

**Comment by friesofdoom** [comment]
Thanks, that would be awesome, I dont think I understand enough about what's going on here to figure it out myself though :)
