### ISSUE TITLE
Props get stuck somtimes

### ISSUE THREAD

**Issue by DFliyerz** [ThatFatKidsMom/Avatar-Prop#2]
Sometimes, seemingly at random, props will get stuck and be unable to be grabbed or despawned by turning off the toggle. The only way to fix this is to reset the avatar. I'd give some more details if I could, but I can't seem to find any pattern to the issue occuring. I'll update this if I notice any patterns.

**Comment by ThatFatKidsMom** [comment]
Definitely odd... could potentially be a low frame rate issue skipping over keys. If it happens again, I would look at the position of where the physbone is located and if its stretched at all. The off animation is supposed to act as a hard reset for anything that may have gone wrong but there may be something I overlooked.

**Comment by ThatFatKidsMom** [comment]
I'll do some testing later and may actually just update some animations regardless to ensure that isn't the case because I felt like it may be slightly under what I needed it to be in order to work 100% of the time.

**Comment by DFliyerz** [comment]
I think there's also a related bug where sometimes other people will see the prop stuck in place and not deactivating with the toggle, but the user of the avatar doesn't. Not sure if you can fix sync issues like that but I thought I'd bring it up.

**Comment by ThatFatKidsMom** [comment]
I've found the issue and it is in fact frame rate dependent. I'm updating the package now. Thank you for bringing this up. The issue was what I mentioned above where keys were skipped and I was only able to reproduce at a less than 10 fps. Ill be making it less likely for this to occur and if it does happen to still occur after updating the package it should at least fix it self when turning the system on and off for sure. It will only require you to update the avatar prop logic layer if you update it.
