### ISSUE TITLE
Can only grab props once

### ISSUE THREAD

**Issue by DFliyerz** [ThatFatKidsMom/Avatar-Prop#3]
While the latest update did fix resetting props, now you can only grab a prop once before it stops being able to be grabbed. As soon as you let go you can't pick a prop back up, and that also seems to break sync for other people because they are able to pick it up for their end but you can't see it.

**Comment by ThatFatKidsMom** [comment]
I cant seem to reproduce this issue after installing the most updated prefab into a fresh project. Also if your only seeing this issue now then there might be something else going on because the only thing that has actually changed fundamentally was adding a transition out of a state when you turn the system off. If your not turning it off the logic still flows the exact same way prior to the update. I know I mentioned that all you had to do was update your FX controller but maybe try doing a fresh install of the prefab and see if the issue persist. Does this issue consistently happen in your case?

**Comment by DFliyerz** [comment]
It was happening consistently but I'll try doing a fresh install.

**Comment by DFliyerz** [comment]
It's definitely happening a lot less often now but it did happen at least once, if it happens again I'll try to see if I can determine what's going on.

**Comment by ThatFatKidsMom** [comment]
Sounds good. Again I appreciate you bringing up any issue you may have with the prefab. If it does happen again, some things to take note of would be to check your debug menu to see if your stuck in a state that isn't one of the "prop dropped" states, write default settings, and FPS. Also does turning off the system not fix it when you get this issue?

**Comment by DFliyerz** [comment]
Turning it off does fix the issue, but I'll try to figure out what's
causing it.

**Comment by DFliyerz** [comment]
Turning it off does fix it, but I'll try to see what's causing it.

**Comment by ThatFatKidsMom** [comment]
Cool thats really useful to know. Did you happen to notice if it only happened when the prop was not in your view? or did it also happen when you were looking straight at it.

**Comment by DFliyerz** [comment]
I wasn't paying close attention but I don't think it was out of my view. I'll try and pay closer attention next time though.

**Comment by DFliyerz** [comment]
So for some reason it seems to have come back after I had initially fixed it by reinstalling, the state's getting stuck in reset root bone pos after letting go. It's only happening sometimes for some reason, but I'll get like streaks of it happening and then a streak of it not happening without me resetting my avatar or anything.

**Comment by ThatFatKidsMom** [comment]
When it happens does turning the system off still fix it when it happens?

**Comment by DFliyerz** [comment]
Yep

**Comment by ThatFatKidsMom** [comment]
I’ll look into it again. If it happens again take note of the value of the parameter named something along the lines of “AvatarProp/DistanceTooFar” and let me know it’s value.

**Comment by DFliyerz** [comment]
It's still getting stuck in reset bone pos, and DistanceTooFar is false.

**Comment by ThatFatKidsMom** [comment]
So for the life of me I cannot reproduce your issue at all even at as low as 5 FPS so I honestly cant say that's its fixed but I have pushed a new release which might do the trick. All I did was go to the "Left pos reset" and "Right pos reset" animations and turned on loop time. I would recommend you just do the same as it'll probably be faster than just downloading the newest release and importing it. Let me know if that does the trick for you.

**Comment by DFliyerz** [comment]
Still running into the same issue unfortunately

**Comment by DFliyerz** [comment]
So I think a pattern I'm seeing is it happens when I start VRchat up and load into the avatar by default, but it seems to stop happening period after resetting the avatar. The only thing I can think of is a parameter being saved inappropriately but that doesn't make much sense.

**Comment by ThatFatKidsMom** [comment]
Yea the only parameter that is "saved" is to enable the prop. Everything else is just handled through contacts. I've tried varying frame rates, culling, multiple projects, and other things to see if I can produce your issue but I just cant get it to break. I know which part is breaking and why its giving you the problem your having but even if it were to fail the system just redoes the process and fixes itself but that doesn't seem to be happening in your case and I have no clue why. I've also asked a couple people I know who use the prefab and they have never had this issue happen to them either. The only thing I can tell you is maybe to try creating a new project installing the prop prefab on an avatar and see if you can replicate it on a new avatar that is made in a new project. Surprisingly that has fixed other issues people have had with it so if that issue really bugs you then it might be worth a shot.

**Comment by DFliyerz** [comment]
I'll probably give it a try, but if that doesn't work it's not a big deal. Now that I know I can pretty much completely fix it by resetting my avatar once a session it's not such a bother. Thanks for the help!

**Comment by DFliyerz** [comment]
So I'm still getting it even after making a new project, it seems like what causes it is DistanceTooFar being false. Not sure what that bool does since it's always true when stuff's working no matter how far I am.

**Comment by ThatFatKidsMom** [comment]
That bool is used to determine when to put the the animator into the reset position states which is essential in order to allow someone to regrab the prop after it is moved a certain distance. Is it possible for you to upload a public version of the avatar your using temporarily and give me the ID so that I can test it in game and see how things are working?

**Comment by ThatFatKidsMom** [comment]
Also just to confirm your not using any mods are you?

**Comment by DFliyerz** [comment]
I am, do you think that could cause issues?

**Comment by ThatFatKidsMom** [comment]
Yea mods can cause some unforeseen issues that I cant really fix because they sometimes literally block certain things that are required for systems to work. That's assuming mods are what's causing the issue. Try running a night without them and see if you still have issues. Also making a public avatar for me to check would help alot to if you can.

**Comment by DFliyerz** [comment]
I'll try running vanilla then if that doesn't work I'll look into making a public version.

**Comment by ThatFatKidsMom** [comment]
sounds good

**Comment by DFliyerz** [comment]
Ok so I'm still getting the issue even with all mods disabled. Interestingly I'm even seeing it in Unity when I use the av 3.0 emulator, if I click the button to reset avatar in the emulator it will set the DistanceTooFar bool to false even though the reciever says it should be true. This happens even on brand new projects so I don't think its anything I did. However I can fix it by disabling the contact sender on "Distance checker" then re-enabling it, so maybe I'll try adding a single frame to the off animation that turns the sender off and on. I'll let you know how that goes.

**Comment by DFliyerz** [comment]
That seemed to work, though I can't be 100% sure that it won't cause any issues with other parts of the system. I just set frame 0 of the "off" animation to set the "Distance checker" contact sender enable to 1, then set it to 0 on frame 14, then back to 1 on frame 28. You might want to try it yourself and make sure it doesn't cause any other issues.

**Comment by ThatFatKidsMom** [comment]
Yea, I tested it right now and it may cause issues initially with some setups although its an easy change to implement. I tested it and I'm just surprised I've never had seen this issue at all until you mentioned resetting in the emulator also triggered it. Once I tried that I was able to see it happen consistently. Kinda weird that the parameter doesn't update properly in the controller despite the contact saying otherwise so might just be a VRC bug that's causing it. Again thanks for bringing it up I'll see if there is anything else that breaks since I'm gonna get on in an hour or so to be able to test it more extensively. If all goes well, I'll push a new release by tomorrow with the changes. Thanks again and let me know if everything still works fine once your able to see if the changes you made work consistently on your end before I push the new release.

**Comment by ThatFatKidsMom** [comment]
So yea I don't get the issue anymore with resetting the avatar via emulator but granted I cant really test to see if the issue doesn't happen anymore as a whole as I've never had it happen to me in game no matter how hard I tried. If you can try installing this and checking to see if it still happens that would be great.
[AvatarProp_1.0.7.zip](https://github.com/ThatFatKidsMom/Avatar-Prop/files/9099813/AvatarProp_1.0.7.zip)
.

**Comment by DFliyerz** [comment]
This seems to have fixed the issues completely, although I'm feeling like it now takes two attempts at grabbing something for it to line up properly. I might just be mis-remembering how things used to work so I'll test a version using the old system and let you know.

**Comment by DFliyerz** [comment]
Turns out that delay was in my head. I'm not sure there's any advantages to doing the method you did where every animation ensures that the distance checker is on and you have it off by default vs my method of having it on by default and just toggling it off and on in the off animation, since whenever you load into the avatar you're going to start in the off position. If you did have a good reason though, I haven't run into any real issues yet.

**Comment by ThatFatKidsMom** [comment]
It's set up that way mainly just for consistency with how everything else is set up and also assuming your variation is set up how I think it is then if someone's frames drops low enough they can potentially skip the key where the contact is off and it could potentially cause the issue to reappear as on their end it would never have reset. That would only happen at low FPS though so its not really that big of a deal. Regardless since everything looks good on your end ill push the release now. Thanks again I appreciate it.
