### ISSUE TITLE
Offset/rotation based on which hand is grabbing

### ISSUE THREAD

**Issue by DFliyerz** [ThatFatKidsMom/Avatar-Prop#4]
I can currently set the offset of my object so that when I grab it with my right hand it's floating in front of my hand, but that makes it so when I grab it with my left hand it's inside my wrist. It'd be useful to have a different object position for when it's grabbed with the left hand or a rotation for when it's grabbed with the left hand.

**Comment by ThatFatKidsMom** [comment]
Why are you changing the rotation of that object to begin with? What is the overarching goal your trying to achieve?

**Comment by DFliyerz** [comment]
I confused myself for a bit on the purpose sorry, I worded this completely wrong because I forgot why I did it. But the reason I did it is because I want my object to be grabbed such that it's vertical while being held, but that requires it to be horizontal when it spawns because the default spawn position has the object being horizontal. I used the save rotation value to make it so the object is vertical when it spawns. The issue I'm trying to deal with is probably unrelated, it's that I moved the position of my object so when I grab it with my right hand it ends up in front of my hand, but that makes it so it ends up inside my wrist when I grab it with my left hand.

**Comment by ThatFatKidsMom** [comment]
Yea so the reason for the difference in position is because the rotation of the container object is rotated 180 degrees if you grab it with your left hand and 0 degrees if you grab it with your right. This is so that the prop is rotated the proper way in both hands. Since you have it offset, the direction it is offset in will flip in the opposite direction when grabbed with the other hand. You would want to animate the position the object your offsetting to be one value for one hand and then the opposite value in the opposite hand. The system wasn’t really designed with people offsetting the position in mind so that’s something you’d have to do yourself.

In regards to having your prop spawn with a specific rotation the way I do it is by adding a source to the rotation constraint of the “rotation” object which is the child of the “position” object. The constraint is then weighted to 1 only on that new source that has my desired rotation values during the “off” and “on” animation states. Once the object is grabbed the weights are animated to whatever it is in the default animation with the only addition being that the new source weight is then animated to 0. So basically you would set it up so that the object in the container is rotated so that the prop is oriented the way you want when grabbed but before it’s grabbed to rotation is constrained to a new object that has your desired values.

**Comment by DFliyerz** [comment]
Sounds good, I'll see if I can fix it on my end and then just keep an eye out for the other issues that are discussed elsewhere.
